### ISSUE TITLE
토큰이 없는 경우 발생하는 에러 예외 처리

### ISSUE THREAD

**Issue by hoseong511** [SpringProject24/FoodieTree_frontend#115]
## Desc
jwtDecode에서 에러 발생

## Detail
- 토큰이 없을 때, jwtDecode에서 에러 발생
<img width="1410" alt="image" src="https://github.com/user-attachments/assets/0c17c492-2002-4dd1-bfa1-352a6b7a80e8">

## Todo
- [ ]  토큰이 없는 경우 jwtDecode 사용하지 않게 하기

**Comment by Maybaba** [comment]
확인했습니다
